@startuml

'' - private
'' + pubblico

package animali {
    class Creatura {
        -name:String
        -peso:double
        -accessori:AccessorioTracciamento[]
        +addAccessorio(accessorio:AccesorioTracciamento):void
        +removeAccessorio(accessorio:AccesorioTracciamento):void

    }

    class AnimaleAnomalo {

    }

    class CriptoAnimale {
        -segretezza:int
    }
}

package accessori {
    class AccessorioTracciamento{}
    class GPS{}
    class Microcamera{}
}

''Ereditarietà - punta vuota verso il padre
Creatura <|-- AnimaleAnomalo
Creatura <|-- CriptoAnimale

AccessorioTracciamento <|-- GPS
AccessorioTracciamento <|-- Microcamera

''0..* => da 0 a * elementi
'' Diamante pieno = composizione
''
Creatura "1" *- "0..*" AccessorioTracciamento

@enduml