@startuml

'' - private
'' + pubblico

package animali {
    class Creatura {
        -name:String
        -peso:double
        -accessori:AccessorioTracciamento[]
        +addAccessorio(accessorio:AccesorioTracciamento):void
        +removeAccessorio(accessorio:AccesorioTracciamento):void
        +consultaAccessori():void
        +mangia():void
        +generaReportCaratteristiche():String
    }

    class AnimaleNormale {
        +emettiVerso():String
    }

    class CriptoAnimale {
        -segretezza:int
        +updateSegretezza(newVal:int)
        +isPericoloso():boolean
    }
}

package accessori {
    class AccessorioTracciamento{}
    class GPS{}
    class Microcamera{}
}
package Driver {
    class Main{
        +main()
    }
}


''Ereditarietà - punta vuota verso il padre
Creatura <|-- AnimaleNormale
Creatura <|-- CriptoAnimale

AccessorioTracciamento <|-- GPS
AccessorioTracciamento <|-- Microcamera

''0..* => da 0 a * elementi
'' Diamante pieno = composizione
''
Creatura "1" o- "0..*" AccessorioTracciamento


Main --> Creatura : istanzia
Main --> AccessorioTracciamento : istanzia
note on link
    Utile caratterizzare la relazione
end note
@enduml